<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-5EVK54D" failures="0" tests="4" name="runner.ScenarioOutlineRunner" time="0.483" errors="1" timestamp="2024-12-02T20:03:34 IST" skipped="0">
  <testcase classname="runner.ScenarioOutlineRunner" name="runScenario" time="0.044"/>
  <system-out/>
  <testcase classname="runner.ScenarioOutlineRunner" name="runScenario" time="0.097">
    <error message="This is failed deliberately" type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException: This is failed deliberately
at steps.ScenarioOutlineSteps.user_enters_name_as_over_form(ScenarioOutlineSteps.java:20)
at âœ½.user enters name as "Diana" over form(file:///F:/Desktop/VimanNagar/May%2021/ATT23NovBDDBasics/src/test/resources/appfeature/ScenarioOutline.feature:9)
]]>
    </error>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="runner.ScenarioOutlineRunner" name="runScenario" time="0.050"/>
  <system-out/>
  <testcase classname="runner.ScenarioOutlineRunner" name="runScenario" time="0.292"/>
  <system-out/>
</testsuite> <!-- runner.ScenarioOutlineRunner -->
